
--1--

--By primary breed--
SELECT
  COALESCE(b.PRIMARY_BREED_NAME,'(none)') AS PRIMARY_BREED,
  COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_BREED b ON b.BREED_KEY = f.BREED_KEY
GROUP BY 1
ORDER BY LICENSES DESC;


--By species
SELECT
  s.SPECIES_NAME,
  COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_BREED   b ON b.BREED_KEY = f.BREED_KEY
JOIN PET_DB.SCHEMA.DIM_SPECIES s ON s.SPECIES_KEY = b.SPECIES_KEY
GROUP BY s.SPECIES_NAME
ORDER BY LICENSES DESC;

--By primary + secondary breed pair
SELECT
  COALESCE(b.PRIMARY_BREED_NAME,'(none)')   AS PRIMARY_BREED,
  COALESCE(b.SECONDARY_BREED_NAME,'(none)') AS SECONDARY_BREED,
  COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_BREED b ON b.BREED_KEY = f.BREED_KEY
GROUP BY 1,2
ORDER BY LICENSES DESC;

--2--

SELECT
  l.CITY_NAME,
  l.STATE_ABBR,
  COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_LOCATION l ON l.LOCATION_KEY = f.LOCATION_KEY
GROUP BY l.CITY_NAME, l.STATE_ABBR
ORDER BY LICENSES DESC, CITY_NAME;

--3--

--By City name--
SELECT d.YEAR, COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY d.YEAR
ORDER BY d.YEAR;

--By year & quarter
SELECT d.YEAR, d.QUARTER, COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY d.YEAR, d.QUARTER
ORDER BY d.YEAR, d.QUARTER;

--By year & month
SELECT d.YEAR, d.MONTH, d.MONTH_NAME, COUNT(*) AS LICENSES
FROM PET_DB.SCHEMA.FACT_PET_LICENSE f
JOIN PET_DB.SCHEMA.DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME
ORDER BY d.YEAR, d.MONTH;
