CREATE OR REPLACE WAREHOUSE PET_WH WAREHOUSE_SIZE = 'XSMALL';
CREATE OR REPLACE DATABASE PET_DB;

CREATE OR REPLACE SCHEMA PET_DB.SCHEMA;
CREATE OR REPLACE SCHEMA PET_DB.STAGE;  

CREATE OR REPLACE ROLE PET_ROLE;

GRANT OWNERSHIP ON DATABASE PET_DB TO ROLE PET_ROLE;

GRANT USAGE ON WAREHOUSE PET_WH TO ROLE PET_ROLE;
GRANT USAGE ON DATABASE PET_DB TO ROLE PET_ROLE;
GRANT USAGE ON SCHEMA PET_DB.SCHEMA TO ROLE PET_ROLE;
GRANT USAGE ON SCHEMA PET_DB.STAGE  TO ROLE PET_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA PET_DB.SCHEMA TO ROLE PET_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PET_DB.STAGE  TO ROLE PET_ROLE;

GRANT USAGE ON DATABASE PET_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PET_DB TO ROLE ACCOUNTADMIN;

CREATE OR REPLACE USER PET_USER
  PASSWORD = 'damg@7370';

  GRANT ROLE PET_ROLE TO USER PET_USER;


  ALTER USER PET_USER
  SET DEFAULT_ROLE = PET_ROLE,
      DEFAULT_WAREHOUSE = PET_WH,
      DEFAULT_NAMESPACE = PET_DB.SCHEMA

      SHOW GRANTS TO USER PET_USER;

      SECONDARY_ROLES = 'ALL';


CREATE USER Akshay PASSWORD='Temp@123' 
CREATE USER Radhika PASSWORD='Temp@123' 

GRANT ROLE pet_role TO USER Akshay;
GRANT ROLE pet_role TO USER Radhika;



create or replace TABLE PET_DB.STAGE.PET_LICENSE (
	LICENSE_ISSUE_DATE VARCHAR(16777216),
	LICENSE_NUMBER VARCHAR(100),
	ANIMAL_NAME VARCHAR(200),
	SPECIES VARCHAR(50),
	PRIMARY_BREED VARCHAR(150),
	SECONDARY_BREED VARCHAR(150),
	ZIP_CODE VARCHAR(10)
);




