CREATE OR REPLACE TABLE DIM_DATE(
  DATE_KEY    INTEGER	PRIMARY KEY,  
  FULL_DATE   DATE,
  YEAR        SMALLINT,
  QUARTER     TINYINT,             
  MONTH       TINYINT,             
  MONTH_NAME  VARCHAR(10),              
  DAY         TINYINT,              
  DAY_NAME    VARCHAR(10),             
  IS_WEEKEND  BOOLEAN   
);

CREATE OR REPLACE TABLE DIM_LOCATION (
  LOCATION_KEY 	INTEGER,
  STATE_FIPS    VARCHAR(10),                      
  STATE_NAME    VARCHAR(100),            
  STATE_ABBR    VARCHAR(2),          
  ZIP_CODE      VARCHAR(10),            
  COUNTY_NAME   VARCHAR(100),                     
  CITY_NAME     VARCHAR(100),         
  CONSTRAINT UQ_LOCATION UNIQUE (ZIP_CODE, CITY_NAME, STATE_ABBR)
);

CREATE OR REPLACE TABLE DIM_SPECIES (
  SPECIES_KEY   INTEGER      PRIMARY KEY,         
  SPECIES_NAME  VARCHAR(50)   UNIQUE
);

CREATE OR REPLACE TABLE DIM_BREED (
  BREED_KEY             INTEGER,         
  SPECIES_KEY           INTEGER      ,
  PRIMARY_BREED_NAME    VARCHAR(100)  ,
  SECONDARY_BREED_NAME  VARCHAR(100),
  CONSTRAINT UQ_BREED UNIQUE (SPECIES_KEY, PRIMARY_BREED_NAME, SECONDARY_BREED_NAME),
  CONSTRAINT FK_BREED_SPECIES FOREIGN KEY (SPECIES_KEY)
    REFERENCES DIM_SPECIES(SPECIES_KEY)
);

CREATE OR REPLACE TABLE FACT_PET_LICENSE (
  FACT_KEY        INTEGER      IDENTITY(1,1) PRIMARY KEY,
  DATE_KEY        INTEGER       ,
  LOCATION_KEY    INTEGER       ,
  BREED_KEY       INTEGER       ,
  LICENSE_NUMBER  VARCHAR(50)   ,
  PET_NAME        VARCHAR(200),
  CONSTRAINT UQ_FACT UNIQUE (LICENSE_NUMBER, DATE_KEY),
  CONSTRAINT FK_FACT_DATE     FOREIGN KEY (DATE_KEY)     REFERENCES DIM_DATE(DATE_KEY),
  CONSTRAINT FK_FACT_LOCATION FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_LOCATION(LOCATION_KEY),
  CONSTRAINT FK_FACT_BREED    FOREIGN KEY (BREED_KEY)    REFERENCES DIM_BREED(BREED_KEY)
);
