MERGE INTO PET_DB.SCHEMA.FACT_PET_LICENSE t
USING (
  SELECT
      pl.LICENSE_NUMBER,
      SUBSTR(pl.ANIMAL_NAME,1,200) AS PET_NAME,
      TO_NUMBER(
        TO_CHAR(
          COALESCE(
            TRY_TO_DATE(TRIM(pl.LICENSE_ISSUE_DATE), 'FMMonth DD, YYYY'),  
            TRY_TO_DATE(TRIM(pl.LICENSE_ISSUE_DATE), 'Mon DD, YYYY'),     
            TRY_TO_DATE(TRIM(pl.LICENSE_ISSUE_DATE))                       
          ),
          'YYYYMMDD'
        )
      ) AS DATE_KEY,
      l.LOCATION_KEY,
      b.BREED_KEY

  FROM PET_DB.STAGE.PET_LICENSE pl

  JOIN PET_DB.SCHEMA.DIM_SPECIES s
    ON UPPER(TRIM(pl.SPECIES)) = UPPER(TRIM(s.SPECIES_NAME))

  LEFT JOIN PET_DB.SCHEMA.DIM_LOCATION l
    ON SUBSTR(REGEXP_REPLACE(pl.ZIP_CODE,'[^0-9]',''),1,5) = l.ZIP_CODE

  JOIN PET_DB.SCHEMA.DIM_BREED b
    ON b.SPECIES_KEY = s.SPECIES_KEY
   AND COALESCE(b.PRIMARY_BREED_NAME,  '∅')
       = COALESCE(NULLIF(UPPER(TRIM(pl.PRIMARY_BREED)),   ''), '∅')
   AND COALESCE(b.SECONDARY_BREED_NAME,'∅')
       = COALESCE(NULLIF(UPPER(TRIM(pl.SECONDARY_BREED)), ''), '∅')
) s
ON t.LICENSE_NUMBER = s.LICENSE_NUMBER
WHEN NOT MATCHED THEN
  INSERT (DATE_KEY, LOCATION_KEY, BREED_KEY, LICENSE_NUMBER, PET_NAME)
  VALUES (s.DATE_KEY, s.LOCATION_KEY, s.BREED_KEY, s.LICENSE_NUMBER, s.PET_NAME)
WHEN MATCHED THEN
  UPDATE SET
    DATE_KEY     = s.DATE_KEY,
    LOCATION_KEY = s.LOCATION_KEY,
    BREED_KEY    = s.BREED_KEY,
    PET_NAME     = s.PET_NAME;
  
  